export const projects = [
  {
    title: 'FindIt',
    description:" Lost and Found System, for university students built with Django and Azure",
    image: '/images/findit.png',
    tags: ['Azure', 'Django', 'Python'],
    source: 'https://github.com/shadowdevsbu/lost-and-found-system.git',
    visit: 'http://shadowdevs-findit.azurewebsites.net/',
    id: 0,
  },
  {
    title: 'Peaches Bot',
    description: "Discord Ai chat bot with auto moderation features",
      image: '/images/1.png',
      tags: ['Discord', 'Python'],
    source: 'https://github.com/nekumartins/Discord',
    visit: 'https://github.com/nekumartins/Discord',
    id: 1,
  },
  {
    title: 'Traffic Sign Detector',
    description:"Road sign classifier, trained on the GTRSB dataset",
    image: '/images/traffic.png',
    tags: ['Python', 'Tensorflow','Scikit-Learn'],
    source: 'https://github.com/nekumartins/AI-With-Python/tree/main/traffic',
    visit: 'https://github.com/nekumartins/AI-With-Python/tree/main/traffic',
    id: 2,
  },
  {
    title: 'Remote Nurse ',
    description: "Monitor the risk of Hypertension of a patient using a classifier model",
    image: '/images/nurse.png',
    tags: ['Flask', 'Python', 'HTML', 'Scikit-Learn', 'Pandas'],
    source: 'https://github.com/nekumartins/Remote-Nurse',
    visit: 'https://github.com/nekumartins/Remote-Nurse',
    id: 3,
  },
  {
    title: 'TicTacToe',
    description:"Wrote a Script to play tic tac toe optimally, utilized the MinMax algorithm",
    image: '/images/2.png',
    tags: ['Python', 'PyGame','Scikit-Learn'],
    source: 'https://github.com/nekumartins/AI-With-Python/tree/main/tictactoe',
    visit: 'https://github.com/nekumartins/AI-With-Python/tree/main/tictactoe',
    id: 4,
  },
  {
    title: 'Saycow',
    description: "Simple Python script that allows you to use the cowsay module to make a cow say whatever you want with different characters",
      image: '/images/tux.png',
      tags: ['Python', 'cowsay'],
    source: 'https://github.com/nekumartins/cowsay',
    visit: 'https://github.com/nekumartins/cowsay',
    id: 5,
  },
  
];

export const TimeLineData = [
  { year: 2021, text: 'Admitted into Uppsala University to study Games Design', },
  { year: 2022, text: 'Admitted into Babcock University to study Computer Science' },
  { year: 2022, text: 'Joined the GDSC Babcock University Chapter' },
  { year: 2023, text: 'Volunteered as a Tutor at Catalyst Babcock University'},
  { year: 2023, text: 'Joined the Babcock University Academic Comittee'},
  { year: 2023, text: 'Accepted into the Software Engineering Program at ALX', },
  { year: 2023, text: 'Member of the GDSC Data Science Core Team' },
  { year: 2023, text: 'Accepted into the Microsoft Learn Ambassador Program'},
  { year: 2023, text: 'Started a position as a Lead Engineer at ShadowdevsBU'},
  { year: 2024, text: 'Advanced to the Beta Milestone of the Microsoft Learn Student Ambassador Program'},
];